### PR TITLE
Implemented AsciiMath support

### PR DESCRIPTION
**Pull request by GarkGarcia**
This is a follow up to #79. I followed the instructions provided in https://github.com/asciidoctor/asciidoctor-mathematical/issues/79#issuecomment-623044299, but I'm not quite sure I made all necessary alterations, since I don't really have a solid understanding of code-base.

@ProgramFan Could you take a look?

### CODE REVIEW

**Comment by GarkGarcia** [comment]
I had a hrd time understanding what is going on in here:

https://github.com/asciidoctor/asciidoctor-mathematical/blob/f81c3a0d3e4ea9fe10fa223010267b1239a030e5/lib/asciidoctor-mathematical/extension.rb#L135

**Comment by GarkGarcia** [comment]
For reference, the idea of this PR is to use `asciidoctor/asciimath` to convert AsciiMath to LaTeX and then render it with mathematical.

Here are some notes on the LaTeX outputted by `asciidoctor/asciimath`:

https://github.com/asciidoctor/asciimath#notes-on-the-latex-output

**Comment by tstumm** [comment]
Travis CI had some hickups, seems like the build passes now.

@ProgramFan What do you think?

**Comment by ProgramFan** [comment]
Thanks for your contribution. With this PR, asciidoctor-mathemtical can now handle all types of stems defined in asciidoc.

**Comment by GarkGarcia** [comment]
> Thanks for your contribution. With this PR, asciidoctor-mathemtical can now handle all types of stems defined in asciidoc.

Great! Thanks!

When could I expect the changes to be released in RubyGems?

**Comment by tstumm** [comment]
See https://rubygems.org/gems/asciidoctor-mathematical/

**Pull request merged**
