### PR TITLE
Fixed the `asciimath` inline-macro processor

### PR DESCRIPTION
**Pull request by GarkGarcia**
This is a follow up to #84:

> This a follow up to [#82 (comment)](https://github.com/asciidoctor/asciidoctor-mathematical/pull/82#issuecomment-632622291). I recently implemented AsciiMath support. It has just been released.
> 
> However, I now realize the `asciimath` inline macro is incorrectly handled. Basically, it is handled in exact the same way the `latexmath` inline macro is. That means the macro is not processing AsciiMath code, it's actually processing LaTeX directly. In other words, currently the `asciimath` inline macro is functionally equivalent to the `latexmath` inline macro. This is an error.
> 
> I'm working on a patch, but I may need some help on it. This issue was cause by my inability to comprehend how inline stem blocks are currently handled. I think I've now got things figured out, but I'd like someone to review the patch in detail to make sure the implementation is not broken again.

### CODE REVIEW

**Comment by GarkGarcia** [comment]
The relevant commit is https://github.com/asciidoctor/asciidoctor-mathematical/pull/85/commits/3b4dfc3e3e30428dbc578f72ca9628782ed3dcee.

**Comment by GarkGarcia** [comment]
@tstumm Please let me know when the patch gets released.

**Comment by GarkGarcia** [comment]
> @tstumm Please let me know when the patch gets released.

@tstumm @ProgramFan Any updates on this?

**Comment by ProgramFan** [comment]
@tstumm Maybe a new release on rubygems?

**Pull request merged**
